### PR TITLE
Change so now are running analytical equaitons instead of rebound

### PR DESCRIPTION
**Pull request by kaimul19**
Unsure if we should wait for me to integrate being able to still use rebound or not, which should be over the coming days but made this request just in case you think its suitable!

### CODE REVIEW

**Review by JCatton — CHANGES_REQUESTED** [review]
ISSUE - 
This is not a modification of the API, we are hoping to have something that we can change by changing either the function name, or an optional argument from True to False (Preferrable). The current implementation, we have neither of these as the planet parameters are different between implementations, which will cause crashes if we try to switch. An ideal scenario would be that we can run MCMC initially using this analytic api to get a nearby estimate, and then can run numerical simulations from then on. Maybe if you could make a function called flux_data_from_params(stellar_params: array, planet_params: array, times: array, analytical: bool = False) and then it calls flux_data_from_params_Analytical (please fix name) or the numerical version from within this function. This is the ideal feature route.
NICE TO DO -
Please review the files that you changed, and check out naming conventions used.
variables and functions should_be_snake_case
Classes should be CamelCase.
Please try to type hint functions, it makes reading the code much easier as we are using numpy a lot and vectorisation can hide the expected output.

**Comment by kaimul19** [comment]
Have acted on commits, see private message on discussion for using rebound for transit calculations.

**Comment by JCatton** [comment]
Very well done acting on commits. Everything is basically perfect from my POV. Just had to do one line of change.
We still have the weird run issue, where i need to specify "../" and you don't for file locations. But that was not a part of this intended change. Good job

**Review by JCatton — APPROVED** [review]
Good Job

**Pull request merged**
